### ISSUE TITLE
Interested in helping

### ISSUE THREAD

**Issue by phoolish** [tomrobison/oauth2-proxy-cookbook#3]
Hello Tom,

I was just about to start developing an oauth2-proxy cookbook for my companies needs (mainly as a kibana authentication layer).  A quick search turned up your repo.  Do you have any interest in cooperating on this?

Thanks.

**Comment by tomrobison** [comment]
That is literally the use case that I was deploying oauth2_proxy for my company.  For reference there is also https://github.com/klamontagne/chef-google_auth_proxy.  

I was thinking of an approach similar to the kibana lwrp cookbook that broke up install, configuration and service.

**Comment by phoolish** [comment]
I saw the other cookbook, but I appreciate the idea of being able to specify multiple providers.  

I like the idea of using multiple lwrp's as well. I have some time over the next couple of days to devote to this, if you'd like to get started.  My first pass would probably be devoted to rhel distros.

**Comment by tomrobison** [comment]
That sounds great!  I should be able to write most of the basic functionality tonight.

**Comment by phoolish** [comment]
Excellent.  Let me know if there is anything I can do to assist.

**Comment by phoolish** [comment]
Did you make any headway?

**Comment by tomrobison** [comment]
I didn't get to work on this cookbook last night, but I'm working on it right now.

**Comment by phoolish** [comment]
No problem.  Ping me if I can be of any assistance.

**Comment by phoolish** [comment]
Tom,

I have a chunk of time over the next 2 days to focus on this.  I need a working prototype by tomorrow.  I'd prefer to work off a shared code base whatever state it's in.  Any chance we can make that happen?

Thanks.

**Comment by tomrobison** [comment]
Sorry for the slow response and not pushing up work in progress.

I just pushed up a branch "mvp" to iterate over.

**Comment by tomrobison** [comment]
@phoolish,

I added resources for a user, install, configure, and service.

My intent is change all of the defaults in the resources to be lazy loaded node attributes.

Let me know what you think so far.

Thanks!!

**Comment by phoolish** [comment]
@tomrobison,

Not a problem at all.  I had something else come up.  I'll take a look at the branch later today and get you some feedback.  Really appreciate whatever work you got through.
